name: Update Deps
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      # used by Gradle to read packages published by other repos
      GH_READ_PACKAGES_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: markelliot/update-gradle-deps@v1
        with:
          push-to-repo-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          commit-user: mellbot
          commit-email: mellbot@users.noreply.github.com

