name: Check PR
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "zulu"
      - name: Build
        run: ./gradlew --no-daemon build
